### ISSUE TITLE
Known bug in webpack that you can add to the readme file.

### ISSUE THREAD

**Issue by Mikael-Sundstrom** [Ihatetomatoes/webpack-101-starter#2]
Without this in the current version, it will open in ``localhost:8080/undefined``. I read that it was caused by late reading of the path. Maybe someone have the same issue.
```js
devServer: {
    open: true,
    openPage: '', //add this to solve it
}
```
And nice tutorial!

**Comment by Ihatetomatoes** [comment]
Thanks Mikael, I did update the readme file.
